# Numpy

NumPy is a popular open-source Python library for scientific computing that provides support for efficient numerical operations on multi-dimensional arrays and matrices. It is a fundamental package for scientific computing with Python and is used widely in data science, machine learning, and other fields that involve numerical computations.

NumPy provides a set of powerful tools for working with arrays, including functions for mathematical, logical, and statistical operations, and tools for manipulating arrays in a variety of ways. It also includes a number of algorithms for performing linear algebra, Fourier transforms, and random number generation.

One of the key benefits of NumPy is its performance. It is implemented in C and provides a fast and efficient interface to numerical routines, making it well-suited for large-scale numerical computations. It also integrates well with other Python libraries, such as SciPy and Matplotlib, which makes it a powerful tool for scientific computing and data analysis.

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# How to use?

1. Creating an array:


```python
import numpy as np

a = np.array([1, 2, 3])
print(a)
# Output [1 2 3]
```

2. Reshaping an array:

```python
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a.reshape((2, 3))
print(b)

```

Output: 


```python
[[1 2 3]
 [4 5 6]]
```

3. Computing the dot product of two arrays:



```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.dot(a, b)
print(c)
```

Output 

```python
32
```

4. Computing the mean of an array:

```python
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.mean(a)
print(b)
# Output 3.0
```

5. Generating a random array:

```python
import numpy as np

a = np.random.rand(3, 2)
print(a)
```

Output:



```python
[[0.55760918 0.85823209]
 [0.10730128 0.82271582]
 [0.89040813 0.54541502]]

```




# Exercises

## Ex1. Create a 3x3 matrix with values ranging from 0 to 8:

In [ ]:
import numpy as np
np.array(range(9)).reshape([3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Ex2. Create a 2x2 identity matrix (1s only on diagonal): without using np.eye(2)

In [4]:
import numpy as np
np.array([[1,0], [0,1]])
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Ex3. Multiply a 5x3 matrix by a 3x2 matrix using np.matmul: 


```python
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
```


In [ ]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
np.matmul(a,b)

array([[1.1570379 , 1.03431298],
       [1.63703574, 1.46805147],
       [0.64019647, 0.38902911],
       [0.97287301, 1.0992849 ],
       [0.08303999, 0.22726165]])

## Ex4.Calculate the mean, median, and standard deviation of a 1-dimensional array:



```python
import numpy as np

a = np.array([1, 2, 3, 4, 5])
```



In [5]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])

print(np.mean(a))
print(np.median(a))
print(np.std(a))

3.0
3.0
1.4142135623730951


In [6]:
a.shape

(5,)

## Ex5. Generate a 4x4 array of random numbers and find the maximum value:

``` python
import numpy as np

a = np.random.rand(4, 4)
```

In [ ]:
a = np.random.rand(4, 4)


0.990292218712436