In [1]:
import numpy as np

### 1. How create the following vector?
### a = (1,1,1,1,1,1)

In [5]:
a = np.array([1,1,1,1,1])
a

array([1, 1, 1, 1, 1])

### 2. Compute the shape of the vector a

In [7]:
a.shape

(5,)

### 3. Now use the vector a to create the following b = (5,5,5,5,5)

In [10]:
b = a*5

### 4.Using the vector b, create a matrix with the following shape (1,5)  

In [12]:
b = b.reshape([1,5])
b.shape

(1, 5)

### 5. Create a random matrix with the followong shape [2,3]

In [14]:
A = np.random.random([2,3])

A

array([[0.80116793, 0.28485543, 0.64104318],
       [0.41454883, 0.32315291, 0.67449635]])

### 6. Transpose matrix

In [15]:
A.T

array([[0.80116793, 0.41454883],
       [0.28485543, 0.32315291],
       [0.64104318, 0.67449635]])

### 7. Create a ones matrix with the following shape f = [[1,2], [3,4]]

In [17]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

### 8. Compute the dot product of the following vectors g = [1,2,3] & h = [3,4,5]

In [18]:
np.dot([1,2,3], [3,4,5])

26

The computation = 1*3 + 4*2 + 5*3 = 3 + 8 + 15 = 26

### 9. Compute the dot product of the following matrix j = [[2,5], [3,6]] & k = [[3,6], [8,3]]

In [19]:
np.dot([[2,5], [3,6]], [[3,6], [8,3]])

array([[46, 27],
       [57, 36]])

### 10. Compute the determinant of j

In [21]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]])
np.linalg.det(b) 

-306.0

### Compute SVD of A = np.array([[3,9,3],[1,7,3],[4,2,1]])


In [22]:
np.linalg.svd(np.array([[3,9,3],[1,7,3],[4,2,1]]))

(array([[-0.76942161, -0.00832115, -0.63868705],
        [-0.58435162, -0.39459242,  0.70910507],
        [-0.25792164,  0.91881858,  0.29874546]]),
 array([12.92370868,  3.41797573,  0.54331927]),
 array([[-0.30365146, -0.89224381, -0.33421067],
        [ 0.95252825, -0.29239533, -0.08482276],
        [-0.02203906, -0.34410166,  0.93867371]]))